default:
    host: "stockanalyzercluster.119ue93.mongodb.net"
    username: "oliveirahenrique70"
    password: "SyM7htklleuO8dvy"
    database: "stock_analyzer"
    collection: "user_base_test"
production:
    host: "stockanalyzercluster.119ue93.mongodb.net"
    username: "oliveirahenrique70"
    password: "SyM7htklleuO8dvy"
